public enum UnitState {
    ShootUp = 1,
    ShootLeft = 2,
    ShootRight = 3,
    WalkUp = 0,
    WalkLeft = 4,
    WalkRight = 5,
    WalkDown = 6,
    JumpRight = 7,
    JumpLeft = 8,
    Die = 10,
    ShootRightUp = 11,
    ShootRightDown = 12,
    ShootLeftUp = 13,
    ShootLeftDown = 14,
    Die2 = 15,
}